[package]
name = "envsense"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "0.8"
thiserror = "1"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
