name: CI
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.89.0
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      # Add LLD with fallback
      - name: Install LLD
        run: |
          sudo apt update
          sudo apt install -y clang lld || echo "LLD installation failed, using default linker"

      - name: Configure LLD
        run: |
          if command -v ld.lld >/dev/null 2>&1; then
            echo 'RUSTFLAGS=-C link-arg=-fuse-ld=lld' >> "$GITHUB_ENV"
            echo "Using LLD linker"
          else
            echo "LLD not available, using default linker"
          fi

      - name: Check Rust formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all --locked -- -D warnings

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier formatting
        run: npm run format:check

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.89.0
      - uses: Swatinem/rust-cache@v2

      # Platform-specific LLD setup
      - name: Install LLD (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y clang lld || echo "LLD installation failed"

      - name: Install LLD (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install llvm lld || echo "LLVM/LLD installation failed"
          echo "CC=clang" >> "$GITHUB_ENV"
          echo "CXX=clang++" >> "$GITHUB_ENV"

      - name: Configure LLD
        run: |
          if command -v ld.lld >/dev/null 2>&1; then
            echo 'RUSTFLAGS=-C link-arg=-fuse-ld=lld' >> "$GITHUB_ENV"
            echo "Using LLD linker"
          else
            echo "LLD not available, using default linker"
          fi

      - name: Run tests
        run: cargo test --all --locked
      - name: Validate baselines
        run: scripts/compare-baseline.sh
