name: CI
on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      
      # Add LLD with fallback
      - name: Install LLD
        run: |
          sudo apt update
          sudo apt install -y clang lld || echo "LLD installation failed, using default linker"
      
      - name: Configure LLD
        run: |
          if command -v ld.lld >/dev/null 2>&1; then
            echo 'RUSTFLAGS="-C link-arg=-fuse-ld=lld"' >> $GITHUB_ENV
            echo "Using LLD linker"
          else
            echo "LLD not available, using default linker"
          fi
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all --locked -- -D warnings
        
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      
      # Platform-specific LLD setup
      - name: Install LLD (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y clang lld || echo "LLD installation failed"
      
      - name: Install LLD (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install llvm || echo "LLVM installation failed"
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
      
      - name: Configure LLD
        run: |
          if command -v ld.lld >/dev/null 2>&1; then
            echo 'RUSTFLAGS="-C link-arg=-fuse-ld=lld"' >> $GITHUB_ENV
            echo "Using LLD linker"
          else
            echo "LLD not available, using default linker"
          fi
      
      - name: Run tests
        run: cargo test --all --locked
      - name: Validate baselines
        run: scripts/compare-baseline.sh
