name: Release

on:
  workflow_run:
    workflows: ["CI", "Test Release Scripts"]
    types: [completed]
    branches: [main]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check if version actually changed and prerequisites passed
  check-version:
    runs-on: ubuntu-latest
    # Only run if the prerequisite workflow succeeded
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      version-changed: ${{ steps.version-check.outputs.VERSION_CHANGED }}
      new-version: ${{ steps.version-check.outputs.NEW_VERSION }}
      tag-name: ${{ steps.version-check.outputs.TAG_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 2 # Need previous commit to compare

      - name: Check if Cargo.toml was changed
        run: |
          echo "Checking if Cargo.toml was changed in commit ${{ github.event.workflow_run.head_sha }}"
          echo "Triggered by workflow: ${{ github.event.workflow_run.name }}"

          # Check if Cargo.toml was modified in the triggering commit
          if git diff --name-only HEAD~1 HEAD | grep -q "^Cargo.toml$"; then
            echo "✅ Cargo.toml was changed - proceeding with release check"
          else
            echo "❌ Cargo.toml was not changed - skipping release"
            exit 78 # Exit with neutral code to skip remaining steps
          fi

      - name: Check version change
        id: version-check
        run: ./scripts/check-version-change.sh

  # Build binaries for multiple targets
  build:
    needs: check-version
    if: needs.check-version.outputs.version-changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            build-type: normal
          - os: macos-latest
            target: universal-apple-darwin
            build-type: universal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      # Build using script
      - name: Build target
        shell: bash
        run: ./scripts/build-target.sh "${{ matrix.target }}" "${{ matrix.build-type }}"

      # Prepare binary using script
      - name: Prepare binary
        shell: bash
        run: ./scripts/prepare-binary.sh "${{ needs.check-version.outputs.new-version }}" "${{ matrix.target }}"

      # Upload binary as artifact
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.target }}
          path: dist/*
          retention-days: 1

  # Create GitHub release
  release:
    needs: [check-version, build]
    if: needs.check-version.outputs.version-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Display downloaded files
        run: ls -la dist/

      - name: Filter release files
        shell: bash
        run: |
          echo "Filtering release files..."
          mkdir -p release-files
          # Copy only non-test files to release-files directory
          find dist/ -name "envsense-v*" -not -name "*-test*" -exec cp {} release-files/ \;
          echo "Release files:"
          ls -la release-files/

      - name: Extract changelog
        shell: bash
        run: ./scripts/create-release.sh "${{ needs.check-version.outputs.new-version }}"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check-version.outputs.tag-name }}
          name: Release ${{ needs.check-version.outputs.tag-name }}
          body_path: changelog_excerpt.md
          files: release-files/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create git tag
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ needs.check-version.outputs.tag-name }}
          git push origin ${{ needs.check-version.outputs.tag-name }}
