name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  id-token: write # Required for cosign keyless signing

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check if version actually changed and prerequisites passed
  check-version:
    runs-on: ubuntu-latest
    # Only run if the prerequisite workflow succeeded
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      version-changed: ${{ steps.version-check.outputs.VERSION_CHANGED }}
      new-version: ${{ steps.version-check.outputs.NEW_VERSION }}
      tag-name: ${{ steps.version-check.outputs.TAG_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0 # Need full history to check tags

      - name: Show trigger information
        run: |
          echo "Triggered by workflow: ${{ github.event.workflow_run.name }}"
          echo "Commit SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "Checking if version needs to be released..."

      - name: Fetch all tags
        run: git fetch --tags

      - name: Check version change
        id: version-check
        run: ./scripts/check-version-change.sh

  # Build binaries for multiple targets
  build:
    needs: check-version
    if: needs.check-version.outputs.version-changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            build-type: normal
          - os: macos-latest
            target: universal-apple-darwin
            build-type: universal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      # Build using script
      - name: Build target
        shell: bash
        run: ./scripts/build-target.sh "${{ matrix.target }}" "${{ matrix.build-type }}"

      # Prepare binary using script
      - name: Prepare binary
        shell: bash
        run: ./scripts/prepare-binary.sh "${{ needs.check-version.outputs.new-version }}" "${{ matrix.target }}"

      # Upload binary as artifact
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.target }}
          path: dist/*
          retention-days: 1

  # Create GitHub release
  release:
    needs: [check-version, build]
    if: needs.check-version.outputs.version-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Display downloaded files
        run: ls -la dist/

      - name: Filter release files
        shell: bash
        run: |
          echo "Filtering release files..."
          mkdir -p release-files
          # Copy only non-test files to release-files directory
          find dist/ -name "envsense-*" -not -name "*-test*" -exec cp {} release-files/ \;
          echo "Release files:"
          ls -la release-files/

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign release binaries
        shell: bash
        run: |
          echo "Signing release binaries with cosign..."
          cd release-files
          for file in envsense-*; do
            if [[ "$file" != *.sha256 && "$file" != *.sig && "$file" != *.bundle ]]; then
              echo "Signing: $file"
              # Create both signature and bundle formats for compatibility
              cosign sign-blob --yes "$file" --output-signature "${file}.sig"
              cosign sign-blob --yes "$file" --bundle "${file}.bundle"
            fi
          done
          echo "Signing completed. Files:"
          ls -la
        env:
          COSIGN_EXPERIMENTAL: 1

      - name: Verify signatures immediately
        shell: bash
        run: |
          echo "Verifying signatures immediately after creation..."
          cd release-files
          for file in envsense-*; do
            if [[ "$file" != *.sha256 && "$file" != *.sig && "$file" != *.bundle ]]; then
              echo "Verifying signature for: $file"
              # Try bundle verification first, then fall back to signature verification
              if [ -f "${file}.bundle" ]; then
                echo "Verifying with bundle: ${file}.bundle"
                cosign verify-blob --bundle "${file}.bundle" "$file"
                echo "✅ Bundle signature verified for: $file"
              elif [ -f "${file}.sig" ]; then
                echo "Verifying with signature: ${file}.sig"
                cosign verify-blob \
                  --signature "${file}.sig" \
                  --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/release.yml@refs/heads/main" \
                  --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
                  "$file"
                echo "✅ Signature verified for: $file"
              else
                echo "❌ No signature or bundle found for: $file"
                exit 1
              fi
            fi
          done
        env:
          COSIGN_EXPERIMENTAL: 1

      - name: Extract changelog
        shell: bash
        run: ./scripts/create-release.sh "${{ needs.check-version.outputs.new-version }}"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check-version.outputs.tag-name }}
          name: ${{ needs.check-version.outputs.tag-name }}
          body_path: changelog_excerpt.md
          files: release-files/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create git tag
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ needs.check-version.outputs.tag-name }}
          git push origin ${{ needs.check-version.outputs.tag-name }}
